image: node:latest

stages:
  - build
  - build-beta

build:
  stage: build
  script:
    - yarn install
    - CI=false yarn build
    - npm publish
    - echo "-- build completed succesfully"
  only:
    - master
build-beta:
  stage: build-beta
  script:
    - yarn install
    - CI=false yarn build
    - npm publish --tag beta
    - echo "-- build completed succesfully"
  only:
    - beta
