image: node:latest

stages:
  - test
  - build
  - build-beta

test:
  stage: test
  script:
    - yarn install
    - yarn lint:check
    - yarn pretty:check

build:
  stage: build
  script:
    - yarn install
    - CI=false yarn build
    - npm publish
    - echo "-- build completed succesfully"
  only:
    - master

build-beta:
  stage: build-beta
  script:
    - yarn install
    - CI=false yarn build
    - npm publish --tag beta
    - echo "-- build completed succesfully"
  only:
    - beta
